@startmindmap RepositoryStructure
<style>
mindmapDiagram {
  .green {
    BackgroundColor #90ee90
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* TIL(Today I Learned)

** C
*** DevelopmentEnvironment
*** Examples

** Elixir
*** Examples
**** FizzBuzz <<green>>
**** hello <<green>>

** Git
*** Github
**** special_files
***** aboutREADME <<rose>>
***** about.gitignore <<rose>>
***** aboutLicense <<rose>>

** JavaScript
*** DOM
**** Document
***** document_querySelector <<rose>>
**** Element

** Linux
*** ubuntu20.04
**** OS_check <<rose>>
**** init_setting <<rose>>

** ShellScript
*** Abstract
**** TypeOfShell <<rose>>
**** aboutShellAndShellScript <<rose>>
*** Examples
**** progressbar <<green>>
**** generalClone <<green>>

** VirtualBox

** paiza
*** LevelUpProblemCollection
**** skillCheckSampleProblem
***** question1
****** question1.c <<rose>>
***** question2
****** question2.c <<rose>>
***** question3
****** question3.c <<rose>>
***** question4
****** question4.c <<rose>>
***** question5
****** question5.c <<rose>>

** plantUML
*** MindMap
**** Github_TIL
***** RepositoryStructure <<rose>>
***** RepositoryStructureJ <<rose>>

** rentalServer
*** sakuraVPS
**** images


legend top left
    yellow : repository-name
    green : code-file
    rose : markdown-file
endlegend

@endmindmap
