@startmindmap RepositoryStructure
<style>
mindmapDiagram {
  .green {
    BackgroundColor #90ee90
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* TIL(Today I Learned)

** C
*** BasicMatters
*** DevelopmentEnvironment
**** forLinux <<rose>>
*** Examples

** Editor
*** VisualStudioCode
**** Shortcut_keys_for_Mac <<rose>>

** Elixir
*** Examples
**** FizzBuzz <<green>>
**** hello <<green>>

** Git
*** Github
**** Github_Pages 
**** special_files
***** aboutREADME <<rose>>
***** about.gitignore <<rose>>
***** aboutLicense <<rose>>

** JavaScript
*** BasicMatters
**** comparison <<rose>>
**** function <<rose>>
**** object <<rose>>
**** reassignment <<rose>>
**** repetition <<rose>>
**** variable <<rose>>
*** DOM
**** Document
***** document_querySelector <<rose>>
**** Element
***** changeElementValue <<rose>>
***** checkElementValues <<rose>>
*** StandardBuiltinObjects
**** Math <<rose>>
**** Number <<rose>>

** Linux
*** Centos
*** get_OS_images <<rose>>
*** ubuntu20.04
**** GUI_image_installation <<rose>>
**** OS_check <<rose>>
**** init_setting <<rose>>
**** server_image_installation <<rose>>

** PHP
*** BasicMatters
**** Calculation <<rose>>
**** Comparison <<rose>>
**** HowToUsePHP <<rose>>
**** Reassignment <<rose>>
**** Repetition <<rose>>
**** StringOutput <<rose>>
**** Time <<rose>>

** Programming

** Redmine

** ShellScript
*** Abstract
**** TypeOfShell <<rose>>
**** aboutShellAndShellScript <<rose>>
*** BasicMatters
**** BasicMatterOfShellScript<<rose>>
**** CompoundCommand <<rose>>
**** CreateShellScript <<rose>>
**** List <<rose>>
**** ShellGramma <<rose>>
*** Examples
**** progressbar <<green>>
**** generalClone <<green>>

** VirtualBox
*** VB_installation <<rose>>
*** VB_settings <<rose>>

** docker

** paiza
*** LevelUpProblemCollection
**** skillCheckSampleProblem
***** question1
****** question1.c <<green>>
***** question2
****** question2.c <<green>>
***** question3
****** question3.c <<green>>
***** question4
****** question4.c <<green>>
***** question5
****** question5.c <<green>>

** plantUML
*** MindMap
**** Github_TIL
***** RepositoryStructure <<green>>
***** RepositoryStructureJ <<green>>

** rentalServer
*** sakuraVPS
**** CreateServer <<rose>>


legend top left
    yellow : repository-name
    green : code-file
    rose : markdown-file
endlegend

@endmindmap
