@startmindmap RepositoryStructureJ

<style>
mindmapDiagram {
  .green {
    BackgroundColor #90ee90
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* TIL(Today I Learned)
** Elixir
*** FizzBuzz <<rose>>
*** hello <<rose>>
** Github
*** 特別なファイル
**** README.mdに関して <<green>>
**** .gitignoreに関して <<green>>
**** Licenseに関して <<green>>
** JavaScript

** ShellScript
*** progressbar <<rose>>

** plantUML
*** マインドマップ
**** Github_TIL
***** リポジトリ構造(英語) <<green>>
***** リポジトリ構造(日本語) <<green>>


legend top left
    黄色 : リポジトリの名前
    緑色 : プログラムのファイル
    ピンク : マークダウンで書かれたファイル
endlegend

@endmindmap
