@startmindmap RepositoryStructureJ

<style>
mindmapDiagram {
  .green {
    BackgroundColor #90ee90
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* TIL(Today I Learned)

** C
*** 開発環境
*** コード例

** Elixir
*** コード例
**** FizzBuzz <<green>>
**** hello <<green>>

** Github
*** 特別なファイル
**** README.mdに関して <<rose>>
**** .gitignoreに関して <<rose>>
**** Licenseに関して <<rose>>

** JavaScript
*** DOM
**** Document
***** HTML等の要素の操作 <<rose>>
**** Element

** Linux
*** ubuntu20.04
**** OSの確認 <<rose>>
**** 最初の設定 <<rose>>

** ShellScript
*** コード例
**** genaralClone <<green>>
**** progressbar <<green>>

** VirtualBox(仮想マシン)

** paiza
*** レベルアップ問題集
**** スキルチェックサンプル問題
***** 問題1
****** question1.c <<rose>>
***** 問題2
****** question2.c <<rose>>
***** 問題3
****** question3.c <<rose>>
***** 問題4
****** question4.c <<rose>>
***** 問題5
****** question5.c <<rose>>

** plantUML
*** マインドマップ
**** Github_TIL
***** リポジトリ構造(英語) <<rose>>
***** リポジトリ構造(日本語) <<rose>>

** レンタルサーバー
*** さくらVPS
**** images

legend top left
    黄色 : リポジトリの名前
    緑色 : プログラムのファイル
    ピンク : マークダウンで書かれたファイル
endlegend

@endmindmap
