@startmindmap RepositoryStructureJ

<style>
mindmapDiagram {
  .green {
    BackgroundColor #90ee90
  }
  .rose {
    BackgroundColor #FFBBCC
  }
}
</style>

* TIL(Today I Learned)

** Elixir
*** コード例
**** FizzBuzz <<green>>
**** hello <<green>>

** Github
*** 特別なファイル
**** README.mdに関して <<rose>>
**** .gitignoreに関して <<rose>>
**** Licenseに関して <<rose>>

** JavaScript
*** DOM
**** Document
***** HTML等の要素の操作 <<rose>>
**** Element

** ShellScript
*** コード例
**** genaralClone <<green>>
**** progressbar <<green>>

** plantUML
*** マインドマップ
**** Github_TIL
***** リポジトリ構造(英語) <<green>>
***** リポジトリ構造(日本語) <<green>>


legend top left
    黄色 : リポジトリの名前
    緑色 : プログラムのファイル
    ピンク : マークダウンで書かれたファイル
endlegend

@endmindmap
